apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      namespace: monitoring
      labels:
        app: grafana
    spec:
      containers:
       - name: grafana
         image: grafana/grafana:10.0.3
         volumeMounts:
           - name: config
             mountPath: "/etc/grafana/"
           - name: dashboards
             mountPath: "/var/lib/grafana/dashboards"
           - name: datasources
             mountPath: "/etc/grafana/provisioning/datasources/"
           - name: dashboardproviders
             mountPath: "/etc/grafana/provisioning/dashboards/"
         resources:
           requests:
            memory: "64Mi"
            cpu: "250m"
           limits:
            memory: "128Mi"
            cpu: "500m"
         ports:
           - name: grafana
             containerPort: 3000
             protocol: TCP
      volumes:
        - name: config
          configMap:
            name: grafana-ini
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboardproviders
          configMap:
            name: grafana-dashboardproviders
        - name: dashboards
          configMap:
            name: dashboards
